[package]
name = "umad"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.6", features = ["form"] }
maud = { version = "0.25", features = ["axum"] }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
